name: phage-lab

channels:
  - bioconda
  - r
  - mikheyev

dependencies:
  - python=3.4
  - biopython
  - r-essentials
  - r-rzmq
  - r-repr
  - r-cairo
  - samtools
  - vcftools
  - bowtie2
  - fastqc
  - r-vcfr
  - r-adegenet
