name: phage-lab

channels:
  - bioconda
  - r
  - mikheyev

dependencies:
#  - python=3.4
#  - biopython
  - r-essentials
  - r-pbdzmq   # for irkernel
  - r-repr     # for irkernel
  - r-crayon   # for irkernel
  - r-devtools # for irkernel
  - libpng # from r channel
  - r-cairo
#  - samtools
#  - vcftools
#  - bowtie2
#  - fastqc
#  - r-vcfr
#  - r-adegenet
